name:                hsearch
version:             0.1.0.0
github:              "andreaconti/hsearch"
license:             BSD-3-Clause
author:              "Andrea Conti"
maintainer:          "contiandrea96@gmail.com"
copyright:           "2019 Andrea Conti"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/andreaconti/hsearch#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - pqueue

tests:
  hsearch-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsearch
    - HUnit
    - test-framework
    - test-framework-hunit
