name:                hsearch
version:             0.1.0.0
github:              "andreaconti/hsearch"
license:             BSD-3-Clause
author:              "Andrea Conti"
maintainer:          "contiandrea96@gmail.com"
copyright:           "2019 Andrea Conti"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            AI Search algorithms implementation
category:            Artificial Intelligence, Algorithms, Search

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/andreaconti/hsearch#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - pqueue >= 1.3.2 && <= 1.4.1.2
  - containers > 0.5.9.1 && <= 0.6.0.1
  - transformers > 0.5.6.1

benchmarks:
  hsearch-benchmarks:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    dependencies:
    - hsearch
    - criterion

tests:
  hsearch-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O
    dependencies:
    - hsearch
    - HUnit
    - test-framework
    - test-framework-hunit
